CREATE TABLE tbCLiente(
	idCli INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nomeCli VARCHAR(45) NOT NULL,
    dtNascCli DATE NOT NULL,
    cpfCli BIGINT(11) NOT NULL,
    emailCli VARCHAR(45) NOT NULL
);
